language: go
go:
    - 1.13
before_install:
install:
    - go get github.com/ICKelin/opennotr/opennotrd
    - go get github.com/ICKelin/opennotr/opennotr
before_script:
script:
    - cd $HOME/gopath/src/github.com/ICKelin/opennotr
    - chmod +x coverage.sh
    # - ./coverage.sh
    - chmod +x build_exec.sh
    - ./build_exec.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)